### ISSUE TITLE
Getting SyntaxError in plugin 'gulp-mocha'

### ISSUE THREAD

**Issue by gihankarunarathne** [sindresorhus/gulp-mocha#117]
I'm using `node 4.2.2` and following dependancies;

```
"devDependencies": {
    "gulp": "^3.9.0",
    "gulp-mocha": "^2.2.0"
  }
```

Here is my gulpfile.js

```javascript
'use strict';

let gulp = require('gulp');
let mocha = require('gulp-mocha');

const paths = {
    lib: ['index.js', 'lib/**/*.js'],
    test: ['test/**/*_test.js']
};

gulp.task('default', function() {
    return gulp.src('./test/ScheduleLimiter_test.js', {
            read: false
        })
        // gulp-mocha needs filepaths so you can't have any plugins before it
        .pipe(mocha({
            reporter: 'nyan',
            bail: true
        }));
});
```

After running `$ gulp` command, it gives following error

```bash
[14:38:03] Using gulpfile ~/schedule-limiter/gulpfile.js
[14:38:03] Starting 'default'...
[14:38:03] 'default' errored after 25 ms
[14:38:03] SyntaxError in plugin 'gulp-mocha'
Message:
    Unexpected token =
Stack:
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (~/schedule-limiter/test/ScheduleLimiter_test.js:12:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

My test files is like below;

```javascript
/**
 * Test cases for Schedule Limiter
 * USAGE:
 *   1. Go to the project directory and run `npm install`
 *   2. Run test cases `gulp test`
 */

'use strict';

let assert = require('assert');
>> let ScheduleLimiter = require('../lib/ScheduleLimiter');
```

**Error was occur in last line.**

**Comment by gihankarunarathne** [comment]
Fixed the error.
This is occurs since I have inserted ES6 syntax. But the error seems to be sound not relating.
