### ISSUE TITLE
SyntaxError in plugin 'gulp-mocha'

### ISSUE THREAD

**Issue by winnemucca** [sindresorhus/gulp-mocha#126]
Starting to work with gulp-mocha on visual studio 2015.   The gulp file itself is working fine.  Set up the tests and got back 

```
SyntaxError in plugin 'gulp-mocha'
```

```
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\HA\VSTS\Applications\HA.Web.Main\Scripts\tests\modules\utility\ha.module.utility.test.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
```

I have node installed.   Did an npm install to check, and commented my tests with mocha.  Is there an error within the gulp-mocha module?

**Comment by najamkhn** [comment]
what version of `node`, `mocha` and `gulp-mocha` are you using?

**Comment by shellscape** [comment]
@winnemucca it's been nearly a year since your first report. please provide an example with the information that @najamkhn requested, or let us know if you've fixed the issue or moved on.
