### ISSUE TITLE
SyntaxError in plugin 'gulp-mocha' Message: Unexpected token =

### ISSUE THREAD

**Issue by DarynHolmes** [sindresorhus/gulp-mocha#137]
Hi,

I am trying to run my tests within Travis-cs, under Node 6 and 4.3. 

Everything works when using Node 6, however I get the following error when running under Node 4.3.

```
[11:27:53] Finished 'build' after 9.78 μs
[11:27:53] Starting 'tests'...
SyntaxError in plugin 'gulp-mocha'
Message:
    Unexpected token =
Stack:
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/travis/build/ruubylimited/bookings-api/app/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/ruubylimited/bookings-api/app/node_modules/mocha/lib/mocha.js:217:14)
[11:27:53] 'tests' errored after 17 ms
[11:27:53] SyntaxError in plugin 'gulp-mocha'
Message:
    Unexpected token =
Stack:
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
```

Are there any recommendations on how to fix this?

FYI: This is intended for an AWS lambda project, that is why we need to use Node 4.3.

**Comment by leftclickben** [comment]
This is an old issue, but it is still open, and it affected me.  Turns out my problem was using the following syntax:

```
const [a, b] = someArray;
```

Changing this to the following equivalent code made it work:

```
const a = someArray[0];
const b = someArray[1];
```

**Comment by leftclickben** [comment]
This is also the same issue as #117.

**Comment by sindresorhus** [comment]
Should be fixed in the latest release: https://github.com/sindresorhus/gulp-mocha/releases/tag/v4.0.0
