### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Wsine** [sindresorhus/gulp-mocha#163]
"version": "4.0.1"

```
~/Workspace/project(master) » gulp                                                                                                                                 

/home/username/Workspace/project/node_modules/gulp-mocha/index.js:2
const dargs = require('dargs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/username/Workspace/project/gulpfile.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by sindresorhus** [comment]
You need to upgrade Node.js.
