### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by freder** [sindresorhus/gulp-mocha#86]
hi,

I'm not sure if it's a gulp-mocha problem per se, but it happens when I'm running test with gulp-mocha, so I'm posting it here.

`gulpfile.js`

```js
var source_file_pattern = path.join(src_dir, '**/*.js');
var test_file_pattern = path.join(test_dir, '*.js');

gulp.task('mocha', function() {
	return gulp.src(test_file_pattern, { read: false })
		.pipe(mocha())
		.on('error', function(err) {
			notifier.notify({
				title: err.plugin,
				message: err.message
			});
		});
});

gulp.task('watch', function() {
	gulp.watch([source_file_pattern, test_file_pattern], ['mocha']);
});

gulp.task('default', ['watch']);
```

`./test/test.js`

```js
var libxml = require('libxmljs');

describe('validation', function() {
	it('should be a valid document', function() {
		//
	});
});
```

so when I run gulp, it watches for file changes and runs the test once something changes. the first time the tests run fine, the second time this happens:

```
[12:35:03] Using gulpfile /Volumes/Macintosh HD 2/Projects/project/code/project.js/gulpfile.js
[12:35:03] Starting 'watch'...
[12:35:03] Finished 'watch' after 14 ms
[12:35:03] Starting 'default'...
[12:35:03] Finished 'default' after 13 μs
[12:35:22] Starting 'mocha'...


  validation
    ✓ should be a valid document


  1 passing (22ms)

[12:35:22] Finished 'mocha' after 129 ms
[12:35:24] Starting 'mocha'...
[12:35:24] 'mocha' errored after 35 ms
[12:35:24] Error in plugin 'gulp-mocha'
Message:
    Module did not self-register.
Stack:
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Volumes/Macintosh HD 2/Projects/project/code/project.js/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Volumes/Macintosh HD 2/Projects/project/code/project.js/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

so this seems to have something to do with [libxmljs](https://github.com/polotek/libxmljs) (or its dependencies). however, when I do `mocha --watch`, I don't get the error.

versions:

```shell
% npm ls | ag '(gulp[^-]|mocha|libxmljs|bindings)'
├─┬ gulp@3.8.11
├─┬ gulp-mocha@2.0.0
├─┬ libxmljs@0.13.0
│ ├── bindings@1.2.1
├─┬ mocha@2.1.0

% node -v
v0.12.0
```

any ideas?

**Comment by freder** [comment]
https://github.com/TooTallNate/node-bindings/issues/17

**Comment by noamokman** [comment]
Same here,
I'm working on a native module and this only pops up on my iojs tests.

Not using libxmljs, but I do use [bindings](https://github.com/TooTallNate/node-bindings)

Node 0.12 works fine with the same package.

iojs tests output:
```bash
node --version
v1.5.1
npm --version
2.7.0
npm test
 
> random-project@0.0.0 test C:\projects\random-project
> gulp test
 
[17:09:26] Using gulpfile C:\projects\random-project\gulpfile.js
[17:09:26] Starting 'jshint'...
[17:09:26] Starting 'mocha'...
[17:09:27] 'mocha' errored after 235 ms
[17:09:27] Error in plugin 'gulp-mocha'
Message:
    Module did not self-register.
Stack:
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at bindings (C:\projects\random-project\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\projects\random-project\lib\file\index.js:5:12)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
[17:09:27] Finished 'jshint' after 437 ms
npm ERR! Test failed.  See above for more details.
Command exited with code 1
```

**Comment by nmccready** [comment]
http://lexsheehan.blogspot.com/2015/03/simple-fix-for-module-did-not-self.html

**Comment by AlexeyGrishin** [comment]
I just met same problem, and proposed solution (reinstall npm modules) did not help - when I use watch + gulp-mocha and my code depends on some lib with 'bindings' library the tests are running fine on the first run, but after any change they fall with the provided error.

I found a workaround: gulp-mocha clears 'require' cache on each run except modules loaded before 'gulp-mocha'. In my project I use 'bcrypt' library which depends on 'bindings', so I just put it to my  gulpfile.js:

```javascript
var gulp = require('gulp')
    , bcrypt = require('bcrypt')
    , mocha = require('gulp-mocha')
```

Hope that helps.

**Comment by rockymadden** [comment]
I have observed this same issue, thanks @AlexeyGrishin.

**Comment by justingreenberg** [comment]
@AlexeyGrishin elegant solution :+1: 

thank you

**Comment by outdooricon** [comment]
Ended up needing to add `require('jsdom');` before my `require('gulp-mocha')` in gulpfile.js as hinted at by @AlexeyGrishin and @rockymadden.

**Comment by elchudi** [comment]
Thanks @AlexeyGrishin , also the same thing is happening with zmq node library

**Comment by superman16885** [comment]
Thanks @AlexeyGrishin, I was using bcrypt in my sequelize user model for password hashing and was facing the same issue. Adding var bcrypt = require('bcrypt') before requiring gulp-mocha fixed the issue.
