### ISSUE TITLE
Unexpected Token *

### ISSUE THREAD

**Issue by dschinkel** [sindresorhus/gulp-mocha#98]
I'm getting the following error when I try to run my mocha test which ultimately also runs some of my code in my server.js:

[10:31:09] SyntaxError in plugin 'gulp-mocha'
Message:
    /Users/dschinkel/code/legacy/projects/search-api/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
Unexpected token *
Stack:
/Users/dschinkel/code/legacy/projects/search-api/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (search-api/node_modules/babel-core/lib/babel/api/register/node.js:177:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (search-api/server.js:5:28)
    at Module._compile (module.js:460:26)
    at normalLoader (search-api/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (search-api/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (search-api/test/bdd/get-obituary-spec.js:3:11)
    at Module._compile (module.js:460:26)
    at normalLoader (search-api/node_modules/babel-core/lib/babel/api/register/node.js:166:5)
    at Object.require.extensions.(anonymous function) [as .js] (search-api/node_modules/babel-core/lib/babel/api/register/node.js:179:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at search-api/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (search-api/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (search-api/node_modules/mocha/lib/mocha.js:422:31)
    at Domain.<anonymous> (search-api/node_modules/gulp-mocha/index.js:53:20)
    at Domain.run (domain.js:197:16)
    at Stream.<anonymous> (search-api/node_modules/gulp-mocha/index.js:51:5)
    at _end (search-api/node_modules/gulp-mocha/node_modules/through/index.js:65:9)
    at Stream.stream.end (search-api/node_modules/gulp-mocha/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (search-api/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at search-api/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickDomainCallback (node.js:381:11)

server.js
------------
'use strict';

var supertestKoa = require('supertest-koa-agent');

var app = module.exports = require('koa')(),
    port = process.env.PORT || 3000;

supertestKoa(app);

app.listen(port, function(){
    console.log('Koa app is listening on port ' + port);
});

myMochaTest.js
---------------------
'use strict';
var api = require('../../server.js');

var port = 3000;
var request = require('co-supertest').agent(api.listen(port, console.log('test app running' + port)));

gulpfile.js
-------------
gulp.task('babel', function () {
    return gulp.src([config.default.src])
        .pipe(babel())
        .pipe(gulp.dest(config.default.build.src));
});

gulp.task('build', ['clean'], function (cb) {
});

gulp.task('clean', del.bind(
    null, ['build/*'], {dot: true}
));

gulp.task('server:start', function() {
    server.listen( { path: config.server.path});
});

gulp.task('server:restart', function() {
    server.restart();
});

gulp.task('mocha-setup', function() {
    return gulp.src([config.test.src.bdd, config.test.src.tdd], { read: false })
        .pipe(babel())
        .pipe(mocha({
            reporter: config.test.mocha.reporter,
            globals: {
                expect: require('chai').expect,
                assert: require('chai').assert
            },
           compilers: {
                js: babel
            }
           }))
        .on('error', gutil.log);
});

gulp.task('development',function() {
    gulp.watch(config.test.root, ['mocha-setup']);
});

gulp.task('default', ['babel','development']);

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow ;)

**Comment by dschinkel** [comment]
fine I'll close this..
